spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: loadBalancerTest
#          uri: lb://MAIN-SERVICE
#          predicates:
#            - Path=/lb/**
#        - id: urlTest
#          uri: http://MAIN-SERVICE:8080
#          predicates:
#            - Path=/url/**
#        - id: bingTest
#          uri: http://bing.com:80
#          predicates:
#            - Path=/bing/**
server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

      instance:
        preferIpAddress: true
        logging:
          level:
            org.springframework.cloud.gateway: DEBUG
            org.springframework.web: DEBUG

  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

