spring:
  application:
    name: MAIN-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/gaminatoriumdb
    driver-class-name: org.postgresql.Driver
    username: gaminatorium
    password: gaminatoriumpass
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

gaminatorium:
  openapi:
    local-url: http://localhost:8080
    prod-url: https://gaminatorium.eu
